config/routes.rb
PersonalApp::Application.routes.draw do

	resources :sessions, only: [:new, :create, :destroy]
	resources :blogs
	resources :projects
	
  root 'static_pages#home'
	match '/about',   to: 'static_pages#about',   via: 'get'
	match '/contact', to: 'contact#new',         	via: 'get'
	match '/contact', to: 'contact#create',       via: 'post'
	match '/signin',  to: 'sessions#new'      ,   via: 'get'
	match '/signout', to: 'sessions#destroy'  ,   via: 'delete'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_secure_password
end

##
# :password_digest  string
# :username    string
##

app/models/blog.rb
class Blog < ActiveRecord::Base
	default_scope -> { order ('created_at DESC') }
end

##
# contents  string
# title  string
# tags string

app/models/message.rb
class Message
	include ActiveModel::Model
	
	attr_accessor :email, :name, :body, :subject
	
	validates_presence_of  :email,:body
	validates_format_of :email, with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
	
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :signed_in_admin, only: [:new, :create, :edit, :update, :destroy]

	def new
		@blog = Blog.new
	end
	
	def create
		@blog = Blog.new(blog_params)
		if @blog.save
			flash[:notice] = "Blog post created"
			redirect_to blogs_url
		else 
			render 'new'
		end
	end
	
	def index
		if params[:tag]
			@blogs = []
			Blog.all.each do |blog|
				if blog.tags.downcase.include? params[:tag]
					@blogs.append(blog)
				end
			end
				@blogs = Kaminari.paginate_array(@blogs).page(params[:page]).per(5)
		else
			@blogs = Blog.page(params[:page]).per(5)
		end
	end
	
	def edit
		@blog = Blog.find(params[:id])
	end
	
	def update
		@blog = Blog.find(params[:id])
		if @blog.update_attributes(blog_params)
		  flash[:notice] = "Blog post updated"
			redirect_to blogs_url
		else
			render 'edit'
		end
	end
	
	def destroy 
		Blog.find(params[:id]).destroy
		redirect_to blogs_url
	end
	
	private
	
		def signed_in_admin
			redirect_to root_url unless session[:admin_id]
		end
		
		def blog_params
			params.require(:blog).permit(:title,:contents, :tags)
		end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

	def new
		@message = Message.new
	end
	
	def create
		@message = Message.new(params[:message])
		if @message.valid?
			ContactMailer.send_message(@message).deliver
			flash[:notice] = "Thank you for getting in touch!"
			redirect_to contact_path
		else
			render 'new'
		end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :signed_in_admin, only: [:new, :create, :edit, :update, :destroy]

  def new
		@project = Project.new
  end
	
  def create
	  @project = Project.new(project_params)
		if @project.save
	    redirect_to root_url
		else
		  render 'new'
	  end
  end
	
  def edit
		@project = Project.find(params[:id])
  end

  def update
	  @project = Project.find(params[:id])
		if @project.update_attributes(project_params)
		  flash[:notice] = "#{@project.name} is updated"
		  redirect_to root_url
		else
		  render 'edit'
		end
  end
	
	def destroy
	  @project = Project.find(params[:id])
    flash[:notice] = "#{@project.name} is destroyed"
		@project.destroy
		redirect_to root_url
	end
	
 private
	
    def project_params
      params.require(:project).permit(:link, :description, :name, :gitlink)
		end
		
		def signed_in_admin 
		  redirect_to root_url unless session[:admin_id]
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	
	def create
		admin = Admin.find_by(username: params["username"])
		if admin && admin.authenticate(params["password"])
			session[:admin_id] = admin.id
			self.current_user = admin
			redirect_to ''
		else
			render 'new'
		end 	
	end
	
	def destroy
		reset_session
		redirect_to :back
	end
	
	private
		
		def current_user=(user)
			@current_user = user
		end
		
		def current_user
			admin_id = session[:admin_id]
			@current_user ||= Admin.find(admin_id)
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		@projects = Project.all(order: "created_at DESC")
	end
	
	def about
	end
	
	def contact
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blogs/edit.html.erb
<%= form_for @blog do |f| %>
	
	<%= f.label :title %>
	<%= f.text_field :title %>
	
	<%= f.label :contents %>
	<%= f.text_area :contents %>
	
	<%= f.label :tags %>
	<%= f.text_field :tags %>
	
	<%= f.submit %>
<% end %>

app/views/blogs/index.html.erb
<%= content_for :page_title, 'Blog' %>
<%= content_for :page_id, 'blog' %>
<div class="introduction">
	<h1>Blog</h1>
</div>

<div id="blog" class="content">

	<%= paginate @blogs %>
	<% for blog in @blogs do %>
		<div class="blog-<%= blog.id %>">
			<h2><%= blog.title %></h2>
			<p class="blog-date"><%= blog.created_at.strftime("%A, %B %d, %Y") %></p>
			<div class="blog-content">
				<%= simple_format(blog.contents) %>
			</div>
			<%= link_to "Comments", '#' %>
			<% if blog.tags %>
				<div class='tags'>
					<p>Tags: 
						<% blog.tags.split(', ').each do |tag| %>
							<%= link_to tag.downcase, blogs_path(tag: tag.downcase) %><% if tag !=  blog.tags.split(' ').last %>,<% end %>
						<% end %>
					</p>
				</div>
			<% end %>
			<% if session[:admin_id] %>
				<%= link_to "Edit", edit_blog_path(blog) %>
				<%= link_to "Delete", blog_path(blog), method: :delete, data: { confirm: "You sure?" } %>
			<% end %>
		</div>
	<% end %>
	
	<%= paginate @blogs %>
	
</div>

app/views/blogs/new.html.erb
<div class="introduction">
	<h1>Create Blog Plost</h1>
</div>

<div class="content" id="new-blog">
	<%= form_for @blog do |f| %>
	
		<div class="text-field">
			<%= f.label :title %>
			<%= f.text_field :title %>
		</div>
		
		<%= f.label :contents %>
		<%= f.text_area :contents %>
		
		<div class="text-field">
			<%= f.label :tags %>
			<%= f.text_field :tags %>
		</div>
		<div class="submit">
			<%= f.submit %>
		</div>
	<% end %>
</div>

app/views/contact/new.html.erb
<%= content_for :page_title, 'Contact' %>
<%= content_for :page_id, 'contact' %>
<div id="contact">
	<div class="introduction">
		<h1>Contact Me</h1>
	</div>
	<div id="email">
		<p><%= mail_to 'axelrod.jeremy@gmail.com'%></p>
		<%= form_for @message, url: contact_path do |f| %>
			<!-- TODO error message -->
			<% if @message.errors.any?  %>
				<ul>
				<% @message.errors.full_messages().each do |message| %>
					<li><%= message %></li>
				<% end %>
				</ul>
			<% end %>

			
			<%= f.label :name %>
			<%= f.text_field :name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>
			
			<%= f.label :subject %>
			<%= f.text_field :subject %>
			
			<%= f.label :body, "Message" %>
			<%= f.text_area :body %>
			
			<%= f.submit "Send Message" %>
			
		<% end %>	
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jeremy Axelrod <%= "|| #{yield(:page_title)}" if yield(:page_title).present? %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container <%= yield(:page_id) %>">
	
		<% if session[:admin_id] %>
			<%= render 'shared/admin_header' %>
		<% end %>

		<%= render 'shared/header' %>
		
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, class: name %>
		<% end %>

		<%= yield %>
		
		<%= render 'shared/footer' %>
		<%= render 'shared/analytics' %>
  </div>
</body>
</html>

app/views/projects/edit.html.erb
<div class="content" id="new-blog">
	<%= form_for @project do |f| %>
	
		<div class="text-field">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		
		<%= f.label :description %>
		<%= f.text_area :description %>
		
		<div class="text-field">
			<p>Format: "http://..."</p>
			<%= f.label :link %>
			<%= f.text_field :link %>
		</div>
		
		<div class="text-field">
			<%= f.label :gitlink, "Github Link" %>
			<%= f.text_field :gitlink %>
		</div>
		
		<div class="submit">
			<%= f.submit %>
		</div>
	<% end %>
</div>

app/views/projects/new.html.erb
<div class="content" id="new-blog">
	<%= form_for @project do |f| %>
	
		<div class="text-field">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		
		<%= f.label :description %>
		<%= f.text_area :description %>
		
		<div class="text-field">
			<p>Format: "http://..."</p>
			<%= f.label :link %>
			<%= f.text_field :link %>
		</div>
		
		<div class="text-field">
			<%= f.label :gitlink, "Github Link" %>
			<%= f.text_field :gitlink %>
		</div>
		
		<div class="submit">
			<%= f.submit %>
		</div>
	<% end %>
</div>

app/views/shared/_admin_header.html.erb
<header id="admin">
	<nav>
		<%= link_to "Sign out", signout_path, method:"delete" %>
		<%= link_to "New Post", new_blog_path %>
		<%= link_to "New Project", new_project_path %>
	</nav>
</header>

app/views/shared/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48583575-1', 'jeaxel.com');
  ga('send', 'pageview');

</script>

app/views/shared/_footer.html.erb
<footer>
	<div id="footer-left">
		<p>&copy;2014 Jeremy Axelrod</p>
	</div>
	<div id="footer-right">
	  <p><%= link_to 'Source', 'http://www.github.com/jeaxelrod/personal-site' %></p>
	</div>
</footer>

app/views/shared/_header.html.erb
<header id="header">
	<div  id="logo">
		<%= link_to "",  root_path %>
	</div>
	<nav id="navagation">
		<%= link_to "Home", root_path %>
		<%= link_to "About", about_path %>
		<%= link_to "Blog", blogs_path %>
		<%= link_to "Contact", contact_path %>
	</nav>
</header>

app/views/shared/_projects.html.erb
<h2>Projects</h2>
<% @projects.each_with_index do |project, index| %>
	<div class="proj-<%= index %>">
		<%= link_to project.link do %>
			<%= image_tag("#{project.name}.png", :alt=> project.name) %>
		<% end %>
		<div class="description">
			<p><%= project.description %></p>
			<% if project.gitlink.present? %>
			  <%= link_to "Source", project.gitlink %>
			<% end %>
			<% if session[:admin_id] %>
				<div class="admin-links">
					<p><%= link_to "Edit Project", edit_project_path(project) %></p>
					<p><%= link_to "Delete Project", project_path(project), method: :delete, data: { confirm: "You sure?" } %></p>
				</div>
			<% end %>
		</div>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<%= content_for :page_title, 'About' %>
<%= content_for :page_id, 'about' %>
<div class="introduction">
	<h1>About me</h1>
</div>
<div class="content">
	<div id="about-left">
		<div class="about-pic">
		</div>
		<h2>Myself</h2>
		<p> 
			I live in the bay area and the internet, places I have called home for 10 years. I enjoy making the world around me a better place.
		</p>
	</div>	
	<div id="about-center">
		<div class="about-pic">
		</div>
		<h2>Developer</h2>
		<p> 
			I'm a ruby on rails <a href="http://github.com/jeaxelrod" class="about-link">developer</a>. I love learning new practices, languages, and frameworks. I'm currently improving my ruby and javascript skills.
		</p>
	</div>
	<div id="about-right">
		<div class="about-pic">
		</div>
		<h2>Designer</h2>
		<p> 
			I design always with the user in mind. I apply my <a href="https://www.google.com/search?q=human-centered+design" class="about-link">human-centered design</a> skills to create apps that are both usable and useful.
		</p>
	</div>
</div>
		
	

app/views/static_pages/home.html.erb
<%= content_for :page_title, 'Web Developer' %>
<%= content_for :page_id, 'home' %>
<div class="introduction">
	<h1>I build web applications for a more usable and beautiful internet.</h1>
</div>

<div class="content">
  <%= render 'shared/projects'%>
</div>